luckynine/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story9/', include('story9.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('portofolio', views.portofolio, name='portofolio'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'


urlpatterns = [
    path('story7', views.index),
    path('story8', views.story8),
    path('getBooks', views.getBooks, name='getBooks'),
]

story7/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    cover = models.URLField(max_length=400)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True)
    publishedDate = models.DateField(max_length=100, blank=True)
    publisher = models.CharField(max_length=200, blank=True)

story7/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.core import serializers
import requests


def index(request):
    return render(request, 'story7.html')

def story8(request):
    return render(request, 'story8.html')

def getBooks(request):
    response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + request.GET['keyword'])
    data = response.json()
    return JsonResponse(data)

story7/templates/story7.html
{% extends "base.html"%}

{% block pageTitle %}

{% endblock pageTitle %}

{% block content%}
    <div class="accordion">
      <center><h2 style="margin-bottom: 37px; ">A TMI from Prinindya</h2></center><br>
        <div class="accordion-item">
          <div class="item-header" id="button1">
            <h1 class="title">Kegiatan selama PJJ</h1>
            <div class="icon1" style="color: white;">&#8595;</div>
            <div class="icon">&#8593;</div>
          
          </div>
          <p class="text" id="body1">
            1. Kuliah <br> 
            2. Rapat <br> 
            3. Kuliah <br> 
            4. Rapat <br> 
            5. Tidur
          </p>
        </div>
  
        <div class="accordion-item">
          <div class="item-header" id="button2">
            <h1 class="title">Pengalaman Organisasi/Kepanitiaan</h1>
            <div class="icon1" id="down2">&#8595;</div>
            <div class="icon" id="up2">&#8593;</div>
          </div>
          <p class="text" id="body2">
            &#10023; Mentor BETIS Fasilkom UI 2020 <br>
            &#10023; HRD Dokumentasi PERAK Fasilkom UI 2020 <br> 
            &#10023; HRD Seminar COMPFEST 2020 <br>
            &#10023; Staff of Tenants UI FASHION WEEK 2020 <br> 
          </p>
        </div>
        <div class="accordion-item">
          <div class="item-header" id="button3">
            <h1 class="title">Things I achieve so far</h1>
            <div class="icon1" id="down3">&#8595;</div>
            <div class="icon" id="up3">&#8593;</div>
          </div>
          <p class="text" id="body3">
            &#x2726; 1st Winner of English Mini Drama Competition 2018 <br>
          </p>
        </div>
      </div>
{% endblock content%}

story7/templates/story8.html
{% extends "base.html"%}
{% load static %}

{% block pageTitle %}

{% endblock pageTitle %}

{% block meta %}
<title>Written by, yours truly.</title>
<script type="text/javascript" src="{% static 'js/story8.js' %}"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"> 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% endblock meta %}

{% block content%}
    <center>
        <div class="header container">
            <h1>Search any books <span class="main-color">here.</span></h1><br>
            <div class="container d-flex">
                <input type="text" class="form-control" name="keyword" id="search-box" placeholder="&nbsp;write the title">&nbsp;&nbsp;
                <button class="btn btn-success" id="search-button">Search</button>
            </div>
        </div><br><br><br>
    </center>
        <div class="container">
            <table id="main-table" style="display: none">
            <tr>
                <th>Cover</th>
                <th>Title</th>
                <th>Author</th>
                <th>Publish Date</th>
                <th>Publisher</th>
            </tr>
            </table>
        </div><br><br><br>
    <script>
        const get_books_url = "{% url 'story7:getBooks' %}?keyword=";
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<style>
html, body, h1, h2, h3, h4, h5, h6, p , span, i, div, input, button {
    font-family: 'Poppins', sans-serif;
}
body {
    background-color: rgb(252, 247, 239);
    color: black;
}

.container {
    width: 1000px;
    margin: auto;
}

table, tr, td, th {
    border: 2px solid black;
    text-align: center;
}

.book-cover {
    width: 150px;
}
.form-control{
        border-radius:25px;
        border:2px solid lightgray;
        align-items: center;
        box-shadow: 0 0px 10px rgba(85, 85, 85, 0.274);
}
.header{
    margin-top: 90px;
}
.main-color{
    color:#f59c3d!important;
}
#search-button {
    border-radius:40px;
}
</style>
{% endblock content%}