luckynine/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story9/', include('story9.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('portofolio', views.portofolio, name='portofolio'),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('create', views.create, name='create'),
    path('list', views.index),
    path('update/<int:update_id>', views.update, name='update'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
]

story5/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.
# memvalidasi di model krn yg ingin di validasi model 

def validate_author(value):
    judul_input = value
    if judul_input == "Einstein":
        message = "maaf" + judul_input + "tidak bisa diposting"
        raise ValidationError(message)

class PostModel(models.Model):
    Mata_Kuliah = models.CharField(max_length=100)
    Keterangan = models.TextField(
        max_length=300,
        validators= [validate_author]
        )
    Pengajar = models.CharField(max_length=100)
    Ruangan = models.CharField(max_length=100)
    SKS = models.CharField(max_length=100)

    LIST_SEMESTER = (
        ('Gasal 2020/2021', 'Gasal 2020/2021'),
        ('Genap 2020/2021', 'Genap 2020/2021'),
        ('Gasal 2019/2020', 'Gasal 2019/2020'),
        ('Genap 2019/2020', 'Genap 2019/2020'),
        ('Gasal 2018/2019', 'Gasal 2018/2019'),
        ('Genap 2018/2019', 'Genap 2018/2019'),
        ('Gasal 2017/2018', 'Gasal 2017/2018'),
        ('Genap 2017/2018', 'Genap 2017/2018'),
        )
    semester = models.CharField(
        max_length=100,
        choices= LIST_SEMESTER,
        default  = 'Maung',
    )
    published = models.DateTimeField(auto_now_add=True)
    
def __str__(self):
    return "{}.{}".format(self.id, self.judul)

story5/forms.py
from django import forms

#import model dari models.py
from .models import PostModel

class PostForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = [
            'Mata_Kuliah',
            'SKS',
            'Ruangan',
            'Pengajar',
            'semester',
            'Keterangan',            
        ]
        widgets = {
            'Mata_Kuliah': forms.TextInput(  
                attrs={
                    'class' : 'form-control', 
                    'placeholder' : 'Tuliskan nama Mata kuliah',
                }
            ),
            'SKS': forms.TextInput(  
                attrs={
                    'class' : 'form-control', 
                }
            ),
            'Ruangan': forms.TextInput(  
                attrs={
                    'class' : 'form-control', 
                }
            ),
            'Pengajar': forms.TextInput(  
                attrs={
                    'class' : 'form-control', 
                    'placeholder' : 'Tuliskan nama dosen anda',
                }
            ),
            'semester': forms.Select(  
                attrs={
                    'class' : 'form-control', 
                }
            ),           
            'Keterangan': forms.TextInput(  
                attrs={
                    'class' : 'form-control', 
                    'placeholder' : 'Catatan tambahan',
                }
            ),
        }
# 'class' : 'form-control' digunakan untuk mengisi sesuai bootstrap

story5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import PostForm
from .models import PostModel

def delete(request, delete_id):
    PostModel.objects.filter(id=delete_id).delete()
    return HttpResponseRedirect("/story5/list")

def update(request, update_id):
    akun_update = PostModel.objects.get(id=update_id)
    data = {
        'Mata_Kuliah' : akun_update.Mata_Kuliah,
        'SKS' : akun_update.SKS,
        'Ruangan' : akun_update.Ruangan,
        'Pengajar' : akun_update.Pengajar,
        'semester' : akun_update.semester,
        'Keterangan': akun_update.Keterangan,
    }
    post_form = PostForm(request.POST or None, initial=data, instance=akun_update)

    if request.method == 'POST':
        #cara ambil data dari input user ke database dg validasi
        if post_form.is_valid():
            post_form.save()
        return HttpResponseRedirect("/story5/list")

    
    context = {
        'pageTitle' : 'Update Form',
        'post_form' : post_form,
    }
    return render(request, 'story5/create.html', context)

def index(request):
    posts = PostModel.objects.all()
    context = {
        'heading' : 'Post',
        'contents': 'List Post',
        'posts' : posts,
    }
    return render(request, 'list.html', context)

def create(request):
    post_form = PostForm(request.POST or None)
    if request.method == 'POST':
        #cara ambil data dari input user ke database dg validasi
        if post_form.is_valid():
            post_form.save()
        return HttpResponseRedirect("/story5/list")

    
    context = {
        'pageTitle' : 'Create Form',
        'post_form' : post_form,
    }
    return render(request, 'create.html', context)

story5/templates/create.html
{% extends "base.html"%}
{% load static %}

{% block Title%}
    {{heading}}
{% endblock Title%}

{% block pageTitle %}
<section id="jumbo-index">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <section name="form">
            <div class="container-fluid">
                <div class="container text-white" style="height: 670px;">
                    <h1>Create Agenda</h1>
                    <form method = "POST" action="">
                        {% csrf_token %}
                        {% for a in post_form %}
                            <div class="form-group">
                                {{a.label}}
                                {{a}}
                            </div>
                        {% endfor %}
                        <button class="btn btn-primary" type="Submit">Tambahkan Matakuliah</button>
                    </form>
                </div>
              </div> 
            
        </section>
      </div>
    </div>
</section>
<style>
    #jumbo-index .jumbotron{
        background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url("/static/main/background.jpg");
        background-size: cover;
        background-position: center;
        height: 1100px;
        width: 100%;
    }
    .btn {
        padding: 7px 30px;
        margin-right: 30px;
        outline: none;
        border: 1px solid #fb7381;
        border-radius: 20px;
        cursor: pointer;
        color: #fb7381;
        background: transparent;
    }
    #jumbo-index .jumbotron{
        background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url("/static/main/background.jpg");
        background-size: cover;
        background-position: center;
        height: 650px;
        width: 100%;
    }
</style>

{% endblock pageTitle %}

story5/templates/list.html
{% extends "base.html"%}
{% load static %}

{% block Title%}
    {{heading}}
{% endblock Title%}

{% block content%}
{% block pageTitle %}
    <section id="jumbo-index">
        <div class="jumbotron jumbotron-fluid">
            <div class="container"> 
                <div class="container-fluid" style="margin-top: 30px;">
                    <div class="container text-white" style="height: 640px;">
                        <h1>List Form</h1>
                        <table class="table">
                            <thead class="table  text-white text-center">
                                <th scope="col">Mata Kuliah</th>
                                <th scope="col">SKS</th>
                                <th scope="col">Ruangan</th>
                                <th scope="col">Pengajar</th>
                                <th scope="col">semester</th>
                                <th scope="col">Keterangan</th>
                                <th scope="col">Hapus</th>
                                <th scope="col">Ubah</th>
                            </thead>
                            <tbody>
                                {% for a in posts %}
                                <tr class="table text-white text-center">
                                    <td> {{a.Mata_Kuliah}} </td>
                                    <td> {{a.SKS}} </td>
                                    <td> {{a.Ruangan}} </td>
                                    <td> {{a.Pengajar}} </td>
                                    <td> {{a.semester}} </td>
                                    <td> {{a.Keterangan}} </td>
                                    <td><a class="btn btn-danger" href="{% url 'story5:delete' a.id %}">Delete</a></td>
                                    <td><a class="btn btn-warning" href="{% url 'story5:update' a.id %}">Update</a></td>
                                </tr> 
                                {% endfor %}
                            </tbody>
                        </table>
                        <a class="btn btn-primary" href="{% url 'story5:create'%}">Add</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

  <style>
    #jumbo-index .jumbotron{
        background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url("/static/main/background.jpg");
        background-size: cover;
        background-position: center;
        height: 650px;
        width: 100%;
    }
  </style>
{% endblock pageTitle%}



{% endblock content%}