luckynine/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story9/', include('story9.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('portofolio', views.portofolio, name='portofolio'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap cdn and css-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/accordion.css' %}">
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <!--script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"--><!--/script-->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/accordion.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
  {% block tambahan %}
  {% endblock tambahan %}
</head>

<body>
    <div class="menu-bar">
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <img src="{% static 'main/maple-leaf.png' %}">
        <a class="navbar-brand" href="#">Written by, Yours Truly. </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link" href="{% url 'main:home' %}">Homepage</a>
            <a class="nav-link" href="{% url 'main:profile' %}">Tentang Penulis</a>
            <a class="nav-link" href="{% url 'main:portofolio' %}">Galeri Foto</a>
            <a class="nav-link" href="/story7/story7">Accordion</a>
            <a class="nav-link" href="/story7/story8">Buku</a>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/story5" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Blog
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/story5/create">Susun Jadwal</a>
            <a class="dropdown-item" href="/story5/list">Jadwal</a>
          </div>
        </li>  
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/story5" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Story 6 
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/story6/create">Jadwal Kegiatan</a>
            <a class="dropdown-item" href="/story6/index">Daftar Nama</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/story9" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Story 9 </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/story9/home">Home</a>
            <a class="dropdown-item" href="/story9/dashboard">Dashboard</a>
            <a class="dropdown-item" href="/story9/register">Register</a>
            <a class="dropdown-item" href="/story9/login">Login</a>
          </div>
        </li>           
          </div>
        </div>
      </nav>
    </div>
</body>
  
  {% block content %}
  {% endblock content %}
  {% block pageTitle %}
  {% endblock pageTitle %}
</html>