luckynine/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story9/', include('story9.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('portofolio', views.portofolio, name='portofolio'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    #path('index', views.indexView),
    path('dashboard', views.dashboardView, name='dashboard'),
    path('home', views.indexView),
    path('register', views.registerView, name='register_url'),
    path('login', views.loginView, name="login_url"),
    path('logout', views.logoutView, name='logout'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'password1', 'password2']

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.contrib import messages
# Create your views here.

from .forms import CreateUserForm

def indexView(request):
    return render(request, 'home.html')

@login_required
def dashboardView(request):
    return render(request, 'dashboard.html')

def registerView(request):
    if request.user.is_authenticated:
        return redirect('story9:home')
    else:
        form = CreateUserForm()
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('story9:login_url')

        return render(request, 'register.html', {'form': form})

def loginView(request):
    if request.user.is_authenticated:
    	return redirect('story9:dashboard')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username = username, password = password)

            if user is not None:
                login(request, user)
                return redirect('story9:dashboard')
            else:
                messages.error(request, 'Username OR password is incorrect')

        return render(request, 'login.html')

def logoutView(request):
    logout(request)
    return redirect('story9:login_url')

story9/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block Title%}
Hello Abroad!
{% endblock Title%}

{% block content%}
  <center>
    <div class="container" style="margin-top: 230px;">
        <h1>Welcome back, <span class="main-color" style="color: rgb(252, 26, 132)">{{user.username}}</span>❤️</h1><br>
        <button type="button" class="btn btn-success"><a style="color: white;" href="{% url 'story9:logout' %}">Logout</a></button>
    </div>
  </center>
{% endblock content%}

story9/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block Title%}
Hi!
{% endblock Title%}

{% block content%}
  <center>
    <div class="container" style="margin-top: 230px;">
      <h1 >Welcome Home 🔮</h1><br>
        <button type="button" class="btn btn-success"><a style="color: white;" href="{% url 'story9:login_url' %}">Login</a></button>
        <button type="button" class="btn btn-info"><a style="color: white;" href="{% url 'story9:register_url' %}">Register</a></button>
    </div>
  </center>
{% endblock content%}

story9/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block Title%}
Log in
{% endblock Title%}

{% block content%}
<div class="container-fluid">
  <div class="row justify-content-center">
      <div class= "col-15 col-sm-10 col-md-3">
          <form class="form-container" method="POST" action="">
            <h5 class="display-5 text-center">LOG IN</h5>
            {% csrf_token %}
              <div class="form-group">
                <label for="id_name"><h6>Name: </h6></label>
                <input class="form-control" type="text" name="username" placeholder="Enter your username" style="margin-bottom: 15px;" required>
                
                <label for="id_password"><h6>Password: </h6></label>
                <input class="form-control" name="password" placeholder="Enter your password" required></input>
                 <!-- {{form.as_p}} -->

              </div>
           <div class="form-group">
              Don't have an account? <br> Click<a href="{% url 'story9:register_url'%}"> here </a>to register
           </div>
           <button type="submit" class="btn btn-block" value="Login" style="background-color: rgb(99, 247, 185); color:black;">Login</button>
           <!-- <input class="btn login_btn" type="submit" value="Login"> -->
          </form><br>
          {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <script>
                    alert("{{ message }}")
                </script>
            {% endfor %}
            </ul>
        {% endif %}
      </div>	
  </div>   
  <style>
    .form-container{
        position:absolute;
        top: 23vh;
        background: rgba(255, 202, 87, 0.986);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px #000;
    }
    .form-control {
        border-radius: 30px;
    }
    .card{
        /* top: 23vh; */
        background: rgb(255, 244, 92);
        padding: 60px;
        margin-right: 30px;
        margin-left: 10px;
        margin-bottom: 40px;
        border-radius: 5px;
    }
    .btn{
        left: 1000px;
    }
      </style>
{% endblock content%}

story9/templates/register.html
{% extends "base.html" %}
{% load static %}

{% block Title%}
Register here
{% endblock Title%}

{% block content%}
<div class="container-fluid" style="margin-bottom: 100px;">
  <div class="row justify-content-center" >
      <div class= "col-15 col-sm-10 col-md-3">
          <form class="form-container" method="POST" action="">
            <h5 class="display-5 text-center">REGISTER</h5>
              {% csrf_token %}
              <div class="form-group">
                 {% for a in form %}
                    {{a.label}}
                    {{a}}
                 {% endfor %}
              </div>
              <div class="form-group">
                 Already have account? Click<a href="{% url 'story9:login_url'%}"> here </a>to log in
             </div>
            <button type="submit" class="btn btn-block" style="background-color: maroon; color: white;">Register</button>
          </form>
          
        </div>
      </div>
  </div>   
  <style>
    .form-container{
        position:absolute;
        top: 23vh;
        background: #eebbb9;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px #000;
    }
    .form-control {
        border-radius: 30px;
    }
    .card{
        top: 23vh;
        background: rgb(255, 244, 92);
        padding: 60px;
        margin-right: 30px;
        margin-left: 10px;
        margin-bottom: 40px;
        border-radius: 5px;
    }
    .btn{
        left: 1000px;
    }
  </style>
{% endblock content%}